name: Validar Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Verificar que test.md no esté vacío
        run: |
          if [ ! -s test.md ]; then
            echo "❌ El archivo test.md está vacío o no existe"
            exit 1
          else
            echo "✅ test.md contiene contenido"
          fi
